FROM mysql:5.7

# COPY hosts /etc/hosts
# COPY ss-engineer-exam /root/ss-engineer-exam
# COPY my.cnf /etc/mysql/mysql.conf.d/
# COPY ss-engineer-exam /docker-entrypoint-initdb.d/.
# ADD ./start.sh /root/start.sh

CMD ["mysqld"]

# CMD ["./root/start.sh"]
# ENTRYPOINT ["docker-entrypoint.sh"]
 
# CMD ["./root/ss-engineer-exam"]
